### ISSUE TITLE
Nimble for MongoDB

### ISSUE THREAD

**Issue by CodebyOmar** [neoighodaro/nimble#1]
Hi, i'm trying to configure Nimble so i can be able to use it with a mongodb databse, i installed the mongodb driver for laravel jensseger\laravel-mongodb., made some tweaks to confing\databse.php file to suite a mongodb connection and i keep getting Unsupported driver [mongodb].

**Comment by neoighodaro** [comment]
According to their documentation

> For usage outside Laravel, check out the Capsule manager and add:

```php
$capsule->getDatabaseManager()->extend('mongodb', function($config)
{
    return new Jenssegers\Mongodb\Connection($config);
});

```

And also adding the corresponding database driver in the config:

```php
'mongodb' => [
    'driver'   => 'mongodb',
    'host'     => env('DB_HOST', 'localhost'),
    'port'     => env('DB_PORT', 27017),
    'database' => env('DB_DATABASE'),
    'username' => env('DB_USERNAME'),
    'password' => env('DB_PASSWORD'),
    'options'  => [
        'database' => 'admin' // sets the authentication database required by mongo 3
    ]
],
```

Did you try this?

**Comment by CodebyOmar** [comment]
Added the code in the databaseComponent.php in nimble, now the instance var in the helper is undefined.
$capsule->getDatabaseManager()->extend('mongodb', function($config)
{
    return new Jenssegers\Mongodb\Connection($config);
});

**Comment by neoighodaro** [comment]
I dont understand what you mean.I don't get you. Post the error you are getting.

**Comment by CodebyOmar** [comment]
![capture](https://cloud.githubusercontent.com/assets/24954601/22178321/dab2c084-dfe7-11e6-80f6-fe34443ffce0.JPG)

this is the error i am getting.tnx

**Comment by neoighodaro** [comment]
`app()` needs a parameter. its a minor bug and should be able to be parameter-less but a quick fix is passing a parameter to `app()`
