### ISSUE TITLE
illuminate\container\container::version() not defined

### ISSUE THREAD

**Issue by CodebyOmar** [neoighodaro/nimble#2]
![capture](https://cloud.githubusercontent.com/assets/24954601/22202747/66abf984-e11e-11e6-977d-98d36682eed7.JPG)
![capture1](https://cloud.githubusercontent.com/assets/24954601/22202749/69abcef2-e11e-11e6-937e-12b3d5606d5a.JPG)

Hi, its me again, after passing a parameter to app() i got another error which is in the image above. The second image is the function where the error is coming from, after passing the version manually it works though, but i don't think that is good.
like $version = '5.3'; instead of $version = app()->version()

**Comment by neoighodaro** [comment]
Yeah that's true. Maybe in future versions I'll create a wrapper over the illuminate container so things like these are trivial
